name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Run eslint using reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: 'src/'
          fail_on_error: true
      - name: Run tsc using reviewdog
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          tsc_flags: 'src/'
          fail_on_error: true